### ISSUE TITLE
rename TDBManagement to TManagement

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#101]
because TDBManagement and TDBConnection are not distinguishable intuitively, what do you think?

**Comment by JanMich** [comment]
i think they are, and we manage more then the rentals, e.g. ID generation

**Comment by ghost** [comment]
i would agree to @JanMich 
If you want we could change it to TManagement

**Comment by ghost** [comment]
Ok #162
