### ISSUE TITLE
Klausurersatzleistung

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#103]
Das wird soweit ich es jetzt verstanden habe Erwartet:

Vorführung
Funktionsumfang darstellen
modulaisiert? klar getrennt? strukturiert?
model view controller-Konzept
Wartbarkeit
Erweiterbarkeit

Sowohl als Präsi als auch als Schriftliche "Dokumentation"

**Comment by frcroth** [comment]
Done
