### ISSUE TITLE
Make sure that only one program instance can exist at a time

### ISSUE THREAD

**Issue by PSchlesselmann** [Herder-IT-Solutions/HerderBib#107]

**Comment by cnmicha** [comment]
this looks interesting http://wiki.freepascal.org/UniqueInstance

**Comment by frcroth** [comment]
Would love to do this but it seems like I have to download something that isn't included in basic LAZARUS. Are there any solutions to include it within the school network so it still compiles?

**Comment by cnmicha** [comment]
There is a howto in the wiki linked above, see this for further help: http://forum.lazarus.freepascal.org/index.php?topic=21773.0

The addon's repository and source code can be found here: https://github.com/blikblum/luipack/tree/master/uniqueinstance

**Comment by frcroth** [comment]
What, am I supposed to include the whole project in our files?

**Comment by cnmicha** [comment]
At least the .pas file, try it out... There's nothing against it in my opinion

**Comment by frcroth** [comment]
So I added two files uniqueinstanceraw and uniqueinstancebase and it works now.
The first thing I do is
`if InstanceRunning then halt;`
