### ISSUE TITLE
auto remove orphans

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#11]
remove book orphans when booktype is deleted
-> sqlite feature?

**Comment by cnmicha** [comment]
wontfix for book-rental history purposes

**Comment by bvorak** [comment]
@cnmicha 
Shouldn't there be an easy manual way to delete these "Orphans" though?
Say the database is getting kind of clogged after a couple of years and you want to delete all entries older than value x ?

**Comment by cnmicha** [comment]
@bvorak Yes, mysql even offers a feature to delete them automatically when a related entity is removed. But this is kind of useless since we have the return-date field in the db and we want to track history of the books rentals, even if the student gets deleted. Clearing the database would be a nice feature, see #30
