### ISSUE TITLE
wrong date function comments

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#113]
this is wrong:
`//Erg: Trägt aktuelles Datum (als Double (nicht lesbar)) als Rückgabedatum in die Datenbank ein
    procedure BBack(BId, SId :LongInt);         `

The date is saved as YYYY-MM-DD in the database, not as double.
I don't know if there are any more wrong comments

**Comment by ghost** [comment]
Well I do not know it either
but today we try it and our database save it as Double Value not formated
I would agree with you that this comment is not necessary

**Comment by cnmicha** [comment]
sorry, we had some inconsistencies on how we save dates. Now as YYYY-MM-DD

**Comment by cnmicha** [comment]
changed now to ddddd (or similar), we will change back and reopen in V2 as we are going to use yyy-dd-mm later
