### ISSUE TITLE
BBack not working

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#115]
uDBManagement, line 240:
`  rental := aoR[1];  `
I think you need to use index 0 instead of 1, and the gui should display a selection window/error message/... if the array length is >1

GUI Group (@frcroth) said it doesn't work

**Comment by cnmicha** [comment]
@frcroth please check if it works with the newer version of uDBManagement in 2148b7ad9b23d3dae97861177cec871e35ab4f0c

**Comment by ghost** [comment]
Yes we made it today with your branch but forgot to merge them.
So now it is working.
