### ISSUE TITLE
handle NULL TDates

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#116]
Should the nil date be pretty as plain text or as date?
0 as plain Text would be 30.12.1899 as date
-693594 as plain text would be 00.00.0000 as date

**Comment by bvorak** [comment]
Is there any chance the user get's to see this date? It's about the return date right?
If so I'd opt for the second proposal. 
Even though the GUI could handle those "not yet set" return dates and display them in an user friendly way.

**Comment by cnmicha** [comment]
nil just means "no date set", so e.g. for the return date, that the book was not returned yet, so replacing it by 0 or minus somewhat would lead to wrong values...

**Comment by ghost** [comment]
No the user should not see this date if we do everything rigth. Yes the return date.
Yes I also guess the second one is better.
Yes @cnmicha but nil is a Object from the type Pointer. The TDate type is an alias for the Double type that does not allow the nil pointer as valid value. So Lazarus gives a compile error back when we try to pass the nil pointer as TDate object.
When this is right I see no other way than these two options also it are "wrong values".

**Comment by cnmicha** [comment]
There is a "Null" value for doubles, I'll check if there is anything compareable for TDate..

**Comment by cnmicha** [comment]
There is not, so the database group will consider every date that is =-1, so =30.12.1899 as NULL value.

**Comment by cnmicha** [comment]
Please use uDBConstants and null check like this:
`if TDateVar = SQLNull then`
working with all integer/float like types
so the -1 value can be changed at one place anytime when neccessary

**Comment by ghost** [comment]
-693594 is the final value

**Comment by cnmicha** [comment]
I will apply to code...
