### ISSUE TITLE
rewrite unit functions to use Entity objects instead of id variables

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#122]
Example (now):
`procedure TDBManagement.BDel(BId:LongInt);
begin
  uDBConn.deleteBook(uDBConn.getBookById(BId));
end;  `

Example (better):
`procedure TDBManagement.BDel(var book:TBook);
begin
  uDBConn.deleteBook(book);
end;  `

to prevent deleted objects being used by the GUI which leads to data inconsistency. TDBConnection provides an easy solution for this by automatically destroying successfully deleted objects, so the GUI cannot display properties of deleted objects.

**Comment by ghost** [comment]
Good idea but the GUI Group asked us last lesson if we could do it with the ID.
We now have it with
function SDel(student:TStudent):Boolean;
function BDel(book:TBook):Boolean;
If the GUI would also like we could change it in every function

**Comment by cnmicha** [comment]
The idea behind the database group's concept was that the gui gets the object, displays its properties (id, ...) and when wanting to delete pass the object so it gets destroyed by TDBCon. When trying to display its properties again, it throws an error (SIGSEV) because the object doesn't exist anymore.

**Comment by JanMich** [comment]
done
