### ISSUE TITLE
deleteReturnedRentalOlderThan

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#129]
where return_date not null
i guess this does(<3) not work anymore because their null is not ourNull=-693594

**Comment by ghost** [comment]
Also this function do not work at all
An error happens in line 602

**Comment by PSchlesselmann** [comment]
*"does" not "do", also in the second comment :P

Btw, it should work now, please test it.

**Comment by cnmicha** [comment]
Btw, there is a constant for -693594 that is called SQLNull and can be changed easily if neccessary. You have to include DBConstants @ghgd-mp
