### ISSUE TITLE
Icon 

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#14]
We should have one

**Comment by frcroth** [comment]
![ico](https://cloud.githubusercontent.com/assets/6863832/22692884/4021451a-ed41-11e6-82dc-3a57a539c87e.png)

**Comment by cnmicha** [comment]
http://megaicons.net/iconspack-178/5688/

**Comment by bvorak** [comment]
@w1ngs how is the logo coming along? :P If you have some beta versions please share :)

**Comment by frcroth** [comment]
Added  @cnmicha s icon temporarly

**Comment by bvorak** [comment]
In case temporary becomes longer we should think about this:
https://icons8.com/license
Which would simply requires us to link the icon source in our "About" tab.

**Comment by frcroth** [comment]
For now I added "Icon: https://icons8.com" in the "Impressum" bc i didn't find the file on  this source. Can someone link it please?

**Comment by bvorak** [comment]
I guess it's this one?
https://icons8.com/icons/download/440/library

**Comment by frcroth** [comment]
Since we have presented it with the temporary icon I guess we won't change it
