### ISSUE TITLE
make the Date readable inside db

### ISSUE THREAD

**Issue by JanMich** [Herder-IT-Solutions/HerderBib#146]
make the Date readable insite the Database; postponed to V2.0

**Comment by cnmicha** [comment]
#113

**Comment by ghost** [comment]
The only solution is to save it as string is`t it ?

**Comment by cnmicha** [comment]
No, SQLite allows saving dates in multiple formats, e.g. ddddd (as we are currently using) or yyyy-mm-dd (as we want to use in V2.0). SQLite converts it automatically to whatever format it thinks is best. In Lazarus, we need to pass the date as string, so we need a function that converts TDate to string in yyyy-mm-dd format.

**Comment by cnmicha** [comment]
FormatDateTime('YYYY-MM-DD', TDate) works

**Comment by ghost** [comment]
Ok so you save it now as Strin in the database?

**Comment by cnmicha** [comment]
No, as date. This issue is only relevant for database group, no need to change anything in other groups' code ever.

**Comment by cnmicha** [comment]
seems to be done already.. strange
