### ISSUE TITLE
SIGSEGV when entering number in BookID field at "Ausleihen"

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#147]
![sigsev140317](https://cloud.githubusercontent.com/assets/7289329/23904403/f8ced524-0884-11e7-9975-8df1a2ace6bc.JPG)

This occurs in GUI branch. ~Probably because it is so many commits behind Dev. branch.
But as it is the only fully compiling branch atm I would prefer to leave it that way until dev. branch compiles again (@ghgd-mp @JanMich)~

**Comment by PSchlesselmann** [comment]
The functions are identical in both branches but this could be a known error, let me have a look.

**Comment by bvorak** [comment]
Nevermind, neither of the branches compiles at the moment, because of good ol' "LargeInt" :P

**Comment by PSchlesselmann** [comment]
It's the mistake we already had a lot of times. I changed it in the database branch.
Michael will merge it soon. (#149)

**Comment by PSchlesselmann** [comment]
According the LargeInt: It is currently changed to Int64, it will be merged soon ~either~ as well.

**Comment by cnmicha** [comment]
The LargeInt problem should be solved now. @bvorak

**Comment by bvorak** [comment]
Yes Dev. Branch us up and running again!

**Comment by PSchlesselmann** [comment]
@cnmicha This is fixed in the database branch.
Do you want to merge it? I could change it in the GUI branch manually either.

**Comment by cnmicha** [comment]
Always merging, no double manual changes because it will become confusing later. I try to merge #152 now
