### ISSUE TITLE
Informationen anzeigen Schüler

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#15]
- Eingabe von Vor- u. Nachname oder ID oder Benutzername führt zur Ausgabe aller Schülerdaten

**Comment by ghost** [comment]
It ist possible with these functions:
function getStudentById(id: Cardinal): TStudent;
function getStudentsByClassName(classN: string): ArrayOfStudents
function getStudentsByLastNamePattern(lastName: string): ArrayOfStudents;
function getStudentsByFirstNamePattern(firstName: string): ArrayOfStudents;
where you get an Array of Students
The student are from the type TStudent, which has getter to get these informations
