### ISSUE TITLE
GUI: Catch Ugly Error when entering letter into one of the ID-fields

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#157]
This not very user friendly error pops up when entering anything other than an integer into any fields that expect an integer:
![uglyerror1](https://cloud.githubusercontent.com/assets/7289329/23998615/e52769d2-0a55-11e7-93e3-ddafaa554145.JPG)

We should either prevent the user from entering anything except numbers altogether
or provide our own more user friendly error...

@frcroth you got an idea how best to achieve this?

**Comment by frcroth** [comment]
fixed
