### ISSUE TITLE
udbmanagement please clean your code

### ISSUE THREAD

**Issue by PSchlesselmann** [Herder-IT-Solutions/HerderBib#159]
Please add sections in your code to make it readable, like in the interface.
Also: Press Strg+D for auto formatting from time to time.
Also: https://github.com/Herder-IT-Solutions/HerderBib/commit/2713671807ab1e1dfc4958c32f9163d7d458e960#commitcomment-21367238
That's not a real problem, but if someone reads the code... it really doesn't look good.

**Comment by ghost** [comment]
Ok #162
