### ISSUE TITLE
getStudentsByFirstLastClassNameBirthdate

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#163]
We have this function but I guess it would be easy done with an SQL-query and it would be much more efficient. 
//Vor: den Vorname, Nachnamen, Klassennamen und Geburtsdatum
//     Geburtsdatum darf ourNil sein; cname darf '' sein, um keine Werte zu übergeben
//Erg: Ein Array von TStudent-Objekten mit den Daten
function getStudentsByFirstLastClassNameBirthdate(fname, lname, cname: string; birth: TDate): ArrayOfStudents;

**Comment by cnmicha** [comment]
what does 'ourNil' mean?

**Comment by cnmicha** [comment]
what does 'cname' mean?

**Comment by ghost** [comment]
const
ourNil = -693594;
cname ist der Klassenname

**Comment by cnmicha** [comment]
You have TDBConstants for that, please use this class instead of creating your own... It's completely unneccessary that every group defines their constants on their own..
See [this](https://github.com/Herder-IT-Solutions/HerderBib/issues/116#issuecomment-285151135) post
Thank you.

**Comment by ghost** [comment]
Ok you are right.
