### ISSUE TITLE
Should we save all barcodes ever createted?

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#174]
Do we want to save barcode png files longer than the print job itself. If yes for how long?
Right now they are dumped as png in the barcode folder. Is there a way to delete them?
If we leave them we might as well reuse them when printing an id again.

**Comment by john0107** [comment]
no

**Comment by john0107** [comment]
The barcodes are deleted as soon as 'latex.pdf' is created.
