### ISSUE TITLE
Multiple errors when editing students

### ISSUE THREAD

**Issue by frcroth** [Herder-IT-Solutions/HerderBib#181]
Management: You should test if there's even an id linked to that student
DB: Make it work! (Errror with Date)

**Comment by PSchlesselmann** [comment]
Please specify the error.

**Comment by cnmicha** [comment]
Date error should be fixed in today's lesson

**Comment by ghost** [comment]
Just successful tested to edit students.
Only The Birthdate do not work!

**Comment by frcroth** [comment]
Birthdays don't work because I have no idea how to implement them.

**Comment by ghost** [comment]
I either do not know but @cnmicha comment that FormatDateTime works.
I will have a look if this could work

**Comment by cnmicha** [comment]
We do not reformat the date anymore, this was for V2. V1 saves dates as seconds since date x in the database.
@frcroth just pass a TDate object to student.setBirth(...)

**Comment by ghost** [comment]
Could be fixed by #188 
("Informationen betrachten und verändern" -> "Schüler" you could now work with the date)

**Comment by frcroth** [comment]
@cnmicha I would love to pass a TDate, if i'd know what it is, but i never found any documentation. Now i have 3 Integers, how can I cast a date?

**Comment by cnmicha** [comment]
See http://www.freepascal.org/~michael/articles/datetime/datetime.pdf

```pascal
var xy:TDate;
xy:=EncodeDate(2017, 03, 21);
student.setBirth(xy);
```

**Comment by ghost** [comment]
Yes like this it is done in the pull request #188
