### ISSUE TITLE
LDAPUser - Database updateinsert function does NOT work

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#192]
Do we work with LDAPUser or not because now when we create new students your function crashes because we do not give the LDAPUser.
Should we always transfer '' or would you misact it or should the GUI handle it ?
Also when we transfer an empty string ('') it crashes
![errorldap](https://cloud.githubusercontent.com/assets/25174759/24268489/3cabb902-100e-11e7-91da-9fb57388dba5.PNG)

**Comment by cnmicha** [comment]
Just pass an empty string to us, I will set the field to NULL

**Comment by ghost** [comment]
The empty String also do not work
now we pass 'ldap'

**Comment by cnmicha** [comment]
no, please pass an empty string, wait for pull #194 and try again :)
