### ISSUE TITLE
updateInsertStudent Mistake

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#213]
In the updateInsertStudent function is a Mistake. You do not write the passed id in the database.
I guess something like 
FieldByName('id').AsLargeInt := student.getId;
is missing.

**Comment by cnmicha** [comment]
No, this way we would assign the standard value (-1) of new created rentals as id. Instead, we want SQL to auto-generate the value for us. I guess you mean #204 :)

**Comment by ghost** [comment]
No, I do not, we would not and we have to do!
The managemen create for every student his id. This ids have to fit some conditions and if you let it auto-generate they would not fit.
By adding this line in line 538 it will be fixed.
Best regards for your exam.
