### ISSUE TITLE
Please only post issues in English

### ISSUE THREAD

**Issue by frcroth** [Herder-IT-Solutions/HerderBib#26]
English is a West Germanic language that was first spoken in early medieval England and is now a global lingua franca.[4][5] Named after the Angles, one of the Germanic tribes that migrated to England, it ultimately derives its name from the Anglia (Angeln) peninsula in the Baltic Sea. It is most closely related to the Frisian languages, although its vocabulary has been significantly influenced by other Germanic languages in the early medieval period, and later by Romance languages, particularly French.
-from Wikipedia, the free encyclopedia

**Comment by bvorak** [comment]
Feel free to translate any issue you want to the language of your liking :)

**Comment by frcroth** [comment]
I think this guideline is widely adopted now
