### ISSUE TITLE
clean database

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#30]
The rental table gets clogged after a couple of years, so maybe we should only keep entries younger than x years? This could be done after program close, but please ask the user before removing.

**Comment by cnmicha** [comment]
gui and management unit group, which functions do you need? @frcroth @JanMich

**Comment by ghost** [comment]
We did a function before.
Perhaps we can move it next lesson to your uDBConnection.

**Comment by frcroth** [comment]
I do not think that this is a concern for the GUI, because we will not be handling the db.

**Comment by cnmicha** [comment]
issue replaced by #63
