### ISSUE TITLE
Feature: Should be possible to create dummy book ID

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#48]
Create dummy book ID without ISBN associated.

Scan dummy book ID and be able to connect with book ID later on

Use case:
Print sheet with dummy IDs in advance and connect books later on

**Comment by cnmicha** [comment]
already done. close issue? @bvorak

**Comment by frcroth** [comment]
Should it?

**Comment by bvorak** [comment]
This still needs discussion, especially with the users if it is really needed. I guess it could be useful depending on the workflow used.
This could guy wise be part of the "Bücher" tab which would require a little makeover though

**Comment by frcroth** [comment]
Adding this would be easy, question is wether this is still planed.
