### ISSUE TITLE
Use cardinal instead of int64 for IDs?

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#50]

**Comment by ghost** [comment]
Yes we should use cardinal instead of int64 or Strings
In my opinion it is not effective to use int64 because ist has an big negative Intervall which we would never use and I am not shure if it will always work on 32 Bit systems.
Cardinal is more effective and more than sufficient!

**Comment by cnmicha** [comment]
code with int64 variables compiles in 32 bit on my system.. And how do you want to prevent the application from crashing because there are coming ids from the database that exceed the cardinal-max value? SQLite does not offer a feature to set the length of primary keys @ghgd-mp

**Comment by ghost** [comment]
well but we generate all ids and the Cardinal Array of 4E9 will probably suffice.
With the int64 there is much more space (which we don`t need) but it also uses the double amount of space

**Comment by cnmicha** [comment]
My fault, I'm sorry. Imo cardinals would be okay, too but we should consistently keep one type

**Comment by ghost** [comment]
ok so from now cardinals ?

**Comment by cnmicha** [comment]
We can try and switch back to int64s if necessary

**Comment by ghost** [comment]
perfect !

**Comment by cnmicha** [comment]
reopened because the code needs to be updated

**Comment by cnmicha** [comment]
why not use int64? the rental id is _generated automatically_ and it uses only less space more (and runs with 32 bit!). The application will crash or destroy - yes really - the data inside the database when rental ids extend the cardinal range. The maximum of SQLite is int64.

**Comment by PSchlesselmann** [comment]
UPDATE: We have decided to use LargeInt.

**Comment by ghost** [comment]
ok so int64 ^^
LargeInt equals int64
http://lazarus-ccr.sourceforge.net/docs/rtl/types/largeint.html

**Comment by cnmicha** [comment]
Lazarus' database classes are only having functions with "LargeInt" in their name, so we used LargeInts in 3a7e939c99754dc00fcfa30442b9ee23597b970a
