### ISSUE TITLE
getAllRentalsByBookAndStudent

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#53]

**Comment by bvorak** [comment]
Isn't there always only one recent rental with a specific book ID and Student ID?
Or do you mean Book "or" Student ID?

**Comment by ghost** [comment]
We have to ask Mrs Brosel if a book for more than one year will be rented for this time or only for each year.
If it is rented for the entire time the book id and the student id have only one rental
But we could also give back an Array of Rentals which have these two ids

**Comment by cnmicha** [comment]
Whether Ms. Brosell says it is going to be rented for two years or not, think about students repeating one year. I think an array is the best solution

**Comment by ghost** [comment]
yes I think you are right
