### ISSUE TITLE
getAllRentalsByBookAndStudent: id is always nil

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#62]
Well the DBConnection grab in the function persist rental on the rental-object id.
This id is nil cause  you say that we should not create this id because the databause do.
But the way it is now it won't work in our opinion.
So we could also make a random id for rantals in the intervall from 0 to 1 Mio
but for that we need a function that controll if a rental id is used like getRentalById(id:Cardinal)

**Comment by cnmicha** [comment]
Did you test that the id is not created automatically by the database? @ghgd-mp

**Comment by JanMich** [comment]
new Rental overrides the old Rental, automatic id does not work ...

**Comment by cnmicha** [comment]
closed in 71b86bc212b4a6aa0b7189f7d870074dc4e9444e
