### ISSUE TITLE
delete returned rentals older than date

### ISSUE THREAD

**Issue by ghost** [Herder-IT-Solutions/HerderBib#63]
In our opinion we should delete all returned rentals by a date parameter.
If we delete all rentals individually that is to much and unnecessary work !
If you need help by this function you can look uDBManagement where it is completly working with a query.
Perhaps also Issue #30 gets solved with this issue.
Dou you agree ?

**Comment by cnmicha** [comment]
@frcroth This is a concern for the GUI because you can display a progress bar while the database is cleaning up (or sth else more user-friendly)

**Comment by frcroth** [comment]
So when is this function called? Is this a problem with the GUI?

**Comment by ghost** [comment]
This possibility is not given or ?
Perhaps there could be an part ind the admin tab that allows to delete every rental until a chooseable date.
This part only would have to Encode the date like the first part of BtInfoStudEditClick and call RDel

**Comment by frcroth** [comment]
So I just ran it with 1.1.2000 and it said it succesfully deleted something like a few million rental relations. I don't think that this is intended.

**Comment by frcroth** [comment]
So it could be an error with the return int

**Comment by ghost** [comment]
![dberror](https://cloud.githubusercontent.com/assets/25174759/24323952/d5ef26b0-117d-11e7-89ec-e7f64cd0cb77.PNG)
?

**Comment by cnmicha** [comment]
??? please specify more detailed what has to be done to reproduce the error @ghgd-mp

**Comment by cnmicha** [comment]
please try again and reopen the issue if the problem persists
