### ISSUE TITLE
new structure in gui

### ISSUE THREAD

**Issue by JanMich** [Herder-IT-Solutions/HerderBib#66]
- query icons not longer necessary
- not longer "TVerwaltung" changed into "TDBManagement"

**Comment by bvorak** [comment]
Both issues are adressed by guy/gui group.

**Comment by JanMich** [comment]
BookRentStu changed into StuRentBook

**Comment by JanMich** [comment]
u have to write student, book, rental and booktype into your uses otherwise it will not work
