### ISSUE TITLE
Licensing: What kind of License?

### ISSUE THREAD

**Issue by bvorak** [Herder-IT-Solutions/HerderBib#74]
As we are already talking about copyright in the GUI-Impressum, we should at some point think about the license we want to use for this Project.

Open Source: yay or nay?
If so: what specific open source license...
If not: why not? ;)

**Comment by cnmicha** [comment]
Comparison chart https://choosealicense.com/appendix/

**Comment by PSchlesselmann** [comment]
Michael, Janne and me think this one should do fine:
https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by bvorak** [comment]
I agree

**Comment by frcroth** [comment]
I guess I'll add it then
