### ISSUE TITLE
db dates as string

### ISSUE THREAD

**Issue by cnmicha** [Herder-IT-Solutions/HerderBib#79]

**Comment by cnmicha** [comment]
@JanMich @ghgd-mp @Tobvolt  sorry, again: why shouldn't the gui call our getDate functions and convert them to the desired date format by themself?

**Comment by JanMich** [comment]
When u save the date as a string insite the database it would be much more easy wenn we dont need to convert it to a TDate and deconvert it to a string again.

**Comment by cnmicha** [comment]
But I don't think the GUI group wants to output it as 2016-02-28, right? I think the TDate type will be easier for conversion

**Comment by JanMich** [comment]
If they will output the date then like dd-mm-yyyy or they-dd-mm or something like this

**Comment by cnmicha** [comment]
DB is always yyyy-mm-dd

**Comment by cnmicha** [comment]
Closed due to [this](https://github.com/Herder-IT-Solutions/HerderBib/issues/79#issuecomment-283114063).

**Comment by ghost** [comment]
Dear @cnmicha,
so I came to the point that it is not clear how we conclude.
if the gui group shoud make the transformation it is ok but we all have to know.

**Comment by cnmicha** [comment]
I thought this is what we decided on Tuesday @ghgd-mp

**Comment by ghost** [comment]
and how does we conclude

**Comment by cnmicha** [comment]
The GUI should convert TDate to the needed string format.
