### ISSUE TITLE
Is it safe to work on newer versions?

### ISSUE THREAD

**Issue by frcroth** [Herder-IT-Solutions/HerderBib#86]
As I wanted to commit only a single line of code, I saw who many files had changed just by me opening the program on a newer OS and Lazarus version. Do you have experience with this? Will it alter the program irreversibly?

**Comment by cnmicha** [comment]
Lazarus creates many backup files and some files inside the lib-folder. You do not need to commit them. Also, it is better do not commit the compiled exe file. When committing from the desktop client, see [gitignore](https://www.atlassian.com/git/tutorials/gitignore) for workflow simplification.
Generally, think of which files you changed and only commit those. By the way, you can see the differences of the old and new version before you commit.
